-- -----------------------------------------------------------
-- Math functions
-- -----------------------------------------------------------
SELECT ABS(-3);

SELECT SQRT(64);

SELECT SQRT(64), COS(DEGREES(90)), SIN(90);

SELECT POW(8,2);

SELECT SIGN(1000), SIGN(0), SIGN(-100000002365236);

DROP TABLE IF EXISTS T;
CREATE TABLE T(
    N INT
);
INSERT INTO T VALUES (12);
INSERT INTO T VALUES (-1), (14000), (140), (16);
SELECT * FROM T;

SELECT MAX(N), MIN(N), AVG(N), SUM(N), COUNT(N) FROM T;

SELECT PI();

SELECT RAND() AS RR;

SELECT T.R FROM (SELECT RAND() AS R) AS T;
SELECT R, CEIL(R), FLOOR(R), ROUND(R) FROM (SELECT RAND()+1 AS R) AS T;
SELECT R, CEIL(R), FLOOR(R), ROUND(R) FROM (SELECT 200+RAND()*200 AS R) AS T;


-- -----------------------------------------------------------
-- Date functions
-- -----------------------------------------------------------
SELECT CURRENT_DATE, CURRENT_TIME, CURRENT_TIMESTAMP, NOW();

SELECT NOW(), ADDDATE(NOW(),INTERVAL 10 DAY);
SELECT NOW(), ADDDATE(NOW(),INTERVAL 10 YEAR);
SELECT NOW(), ADDDATE(NOW(),INTERVAL -10 YEAR);
SELECT NOW(), ADDDATE(NOW(),INTERVAL 10 MONTH);

SELECT NOW(), ADDTIME(NOW(),"10");
SELECT NOW(), ADDTIME(NOW(),"1:10:12");

SELECT DATE(NOW()),TIME(NOW()),YEAR(NOW()),MONTH(NOW()),DAY(NOW()),HOUR(NOW()),MINUTE(NOW()),SECOND(NOW());

SELECT DATE_FORMAT(NOW(),"%Y (%y) - %W (%w) - %M (%m) - %p - %j");

SELECT TIME_FORMAT(NOW(),"%H - %i - %S");

SELECT DAYNAME(NOW()), DAYOFYEAR(NOW()), DAYOFMONTH(NOW()), DAYOFWEEK(NOW());

SELECT EXTRACT(DAY FROM NOW());

SELECT LAST_DAY(NOW()),DAY(LAST_DAY(NOW())),DAYNAME(LAST_DAY(NOW())), MONTHNAME(NOW());

SELECT TIME_TO_SEC("2:10:30");
SELECT SEC_TO_TIME(7830);

SELECT DATEDIFF("2020-01-01","2020-02-15");
SELECT TIMEDIFF("12:10:30","13:11:31"),TIME_TO_SEC(TIMEDIFF("12:10:30","13:11:31")) AS SECOND;

SELECT CONV(12,10,2), CONV(1100,2,10);