DROP DATABASE IF EXISTS Test;
CREATE DATABASE Test;
-- SHOW DATABASES;

USE Test;

DROP TABLE IF EXISTS Product;
CREATE TABLE Product(
	ID 			INT 		NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Name		VARCHAR(50),
    ColorID		INT
);

DROP TABLE IF EXISTS Color;
CREATE TABLE Color(
	ID 			INT 		NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Name		VARCHAR(50)
);

INSERT INTO Color VALUES (1, "Yellow");
INSERT INTO Color VALUES (2, "Green");
INSERT INTO Color VALUES (3, "Red");

INSERT INTO Product VALUES (NULL, 'Hat', 'yellow');
INSERT INTO Product VALUES (NULL, 'Hat2','green');

-- SELECT * FROM Product;